### PR TITLE
Small Feature Improvements and bugfix

### PR DESCRIPTION
**Pull request by rocketinventor**
This pull request fixes an issue where lines of text inside the eBook would get too long and would get cut off.

It also changes the output directory to "Books" - but it can be specified in the command line.

### CODE REVIEW

**Comment by GatoLoko** [comment]
You have combined multiple things in a single pull request, a new feature (directory) and a change to the generated book.
I will reject the pull request because this kind of independent changes should be merged independently.

As for the changes:

- Defaulting to a new directory changes the current behavior and may break some use cases. For example, I usually call the script from somewhere different than the source directory, say "/home/user/MyBooks", and expect the generated book to end in there, not into a new sub-directory. Though I can see how this may be interesting to some people, I'm not sure it's a good idea to make it the default option.

- For the "pre" fixing, you have replaced the opening tag, but not the closing one, and rely on BeautifulSoup to fix the mess. This may work most of the time, but is a bad practice. If we do this, we should replace both the opening and closing, and if necessary, fix anything in the middle. Also, the pre tag is very useful in some situations, and should be properly supported by any epub reader. Maybe we could add CSS to alter it's output instead of replacing it entirely.

**Comment by rocketinventor** [comment]
Okay, thank you for the feedback!

As far as the `pre` fixing: The purpose of the changes here was to address issue #21. I noticed that the book summary (in `<p>` tags rendered fine, everywhere, but the chapters themselves did not. I see that it has also been addressed in #24 and also with your last commit ([2603457](https://github.com/GatoLoko/Wattpad2Epub/commit/26034571010a3ec351729e833914ed6cf43362ac)), which seems like a much better solution. I am not sure, though, where you see that I only changed the opening tags and not the closing ones... Could you please explain/point out where you see that?

As far as the directory changes: I get errors whenever I try to run the script from anywhere that is not the script directory itself. If the script is supposed to work elsewhere (i.e. when being called from the home directory), then there needs to be a new issue to address this. Also, the readme should be updated to make this more clear. In this case, though, I agree that the directory flag should be optional.

**Comment by GatoLoko** [comment]
> I am not sure, though, where you see that I only changed the opening tags and not the closing ones... Could you please explain/point out where you see that?

On [b020831](https://github.com/GatoLoko/Wattpad2Epub/pull/18/commits/b0208311ac96a2bf9f6bdfdd1fa24ba7ffc5fdb1) you replace the `<pre>` tag, but not the `</pre>`

> As far as the directory changes: I get errors whenever I try to run the script from anywhere that is not the script directory itself. If the script is supposed to work elsewhere (i.e. when being called from the home directory), then there needs to be a new issue to address this. Also, the readme should be updated to make this more clear. In this case, though, I agree that the directory flag should be optional.

I hadn't tested calling it from a different directory, but you are right, it fails to find the CSS and HTML files. I've just tried a fix for this and will commit it in a few minutes.

As for the readme, it is a mess of its own, and needs several changes. I'll open a new issue for that.

**Comment by rocketinventor** [comment]
> On b020831 you replace the `<pre>` tag, but not the `</pre>`

You mean the part: `.replace('pre>', 'p>')`? That should match the closing tags, too. i.e. `</` _`pre>`_ ---> `</` _`p>`_, no?


> For example, I usually call the script from somewhere different than the source directory, say "/home/user/MyBooks", and expect the generated book to end in there...

Is this something that used to work but then stopped working later on (before bb8ddb9)? - I saw the commit, thank you!

**Comment by GatoLoko** [comment]
> You mean the part: `.replace('pre>', 'p>')`? That should match the closing tags, too. i.e. `</` _`pre>`_ ---> `</` _`p>`_, no?

You are right. I've been making this kind of mistakes lately (lack of sleep), sorry.

Still, if I remember it right, you should not nest p tags inside p tags, and beautifulsoup would close the opening one before the history text, resulting in an empty paragraph, and remove the orphaned closing tag at the end.

This kind of "autofix" done by beautifulsoup may be helpful, or may cause all kind of weird results when it does something you don't expect, so I try to avoid it as much as possible.

> Is this something that used to work but then stopped working later on (before [bb8ddb9](https://github.com/GatoLoko/Wattpad2Epub/commit/bb8ddb95bf52ea6d299f45e08a7b6b7530161777))? - I saw the commit, thank you!

I had it working thanks to my own custom environment, that wouldn't be useful for anybody else. This commit makes it work in a more generic way without my custom settings, which is the right way to do it since it's useful for more people.

**Pull request closed without merging**
