### PR TITLE
Remove all <pre> and </pre> tags

### LINKED ISSUE #21: Bad format because of <pre> tag
Every chapter is enclosed in <pre> tags. This breaks the display of the epub, because every paragraph is displayed in a single line without line break.

### PR DESCRIPTION
**Pull request by silbaer**
pretty simple method to remove the annoying pre tag

### CODE REVIEW

**Comment by GatoLoko** [comment]
I'm still unconvinced about removing "pre" tags, as I've seen it used properly in some stories (can't remember which one though).

As per the [epub standard](https://www.w3.org/publishing/epub3/), the tag should be supported by readers, so if there isn't a badly writen story, this could be a reader problem.

One problematic reader was calibre, which uses a custom CSS. With their 4.0 release they changed said CSS in relation with "pre" tags and should now work better.

 Have you explored any possible alternatives before resorting to this?

**Comment by silbaer** [comment]
> I'm still unconvinced about removing "pre" tags, as I've seen it used properly in some stories (can't remember which one though).

Yes that can be a problem.
 
> As per the [epub standard](https://www.w3.org/publishing/epub3/), the tag should be supported by readers, so if there isn't a badly writen story, this could be a reader problem.
> 
> One problematic reader was calibre, which uses a custom CSS. With their 4.0 release they changed said CSS in relation with "pre" tags and should now work better.

The "pre" tag works like expected as I see, but the result is not readable on my Tolino. I guess there is a CSS on the Wattpad page for the "pre" tag or the classes inside this tag, that makes the display on the webpage correct/readable.
 
> Have you explored any possible alternatives before resorting to this?

The selection of the "pre" tag is to select the content of the story, so the inner html is what we want, right? I have tried to get the children of the  "pre" tag, and ended with a nested loop like this:

```
def get_page(text_url):
    rs = get_html(text_url).select('pre')
    text = []
    for pretag in rs:
        for child in pretag:
            text.append(child)
    return text
```
My understandig is, the elements of text[] are `tag` objects, but this line 
```
for j in get_page(page_url):
    text.append(j.prettify())
```
throws an `AttributeError: 'NavigableString' object has no attribute 'prettify'` error. 
I don't know python (first time I used python) and the used packages, so I am unsure whats going wrong. Using `str(j)` instead of `j.prettify()` seems to work, but, as I said, I am unsure what exactly is going on. :)

**Comment by GatoLoko** [comment]
> > I'm still unconvinced about removing "pre" tags, as I've seen it used properly in some stories (can't remember which one though).
> 
> Yes that can be a problem.

It seems I was wrong. I've been checking Wattpad's html and they are using this "pre" tag around the story as some form of container, so we can remove it safely as long as we don't affect any other instances.

Your code, as is, would remove those other instances of "pre", but I've figured an even simpler way to fix this.

> The selection of the "pre" tag is to select the content of the story, so the inner html is what we want, right? I have tried to get the children of the "pre" tag, and ended with a nested loop like this:
> 
> ```
> def get_page(text_url):
>     rs = get_html(text_url).select('pre')
>     text = []

It's simpler to use: `rs = get_html(text_url).select_one('pre').findChildren()`

select_one gives us the first it can find (which is the one we want in this case, there are more around comments and other things), and findChildren gives us whatever is INSIDE that tag, solving this problem in a simple, quick and safe way.

> My understandig is, the elements of text[] are `tag` objects, but this line

That "text = []" creates an empty list. You can add whatever you want to the list. It is used in get_chapter to store individual 'tags' or entire sections with multiple tags of the original html that we want to preserve, and later we by join them with `"".join(text)` into a single string that can be used as content for the epub chapter.

> ```
> for j in get_page(page_url):
>     text.append(j.prettify())
> ```
> 
> throws an `AttributeError: 'NavigableString' object has no attribute 'prettify'` error.

The problem here is that you are taking a [Soup](https://www.crummy.com/software/BeautifulSoup/bs4/doc/) from get_page and "spliting it" into several parts, which in this case are individual lines of the original html, so you can do something to each individual parts (which are NavigableString), and those parts do not have a "prettify". The prettify method is meant to "align and indent" the full soup, and can't be applied to individual lines.

**Comment by GatoLoko** [comment]
Since there is a better way to fix this problem, I'll close this pull request.

**Pull request closed without merging**
