### PR TITLE
Add 'python' variant

### PR DESCRIPTION
**Pull request by hrueschwein**
On some devices you need write not "python3", but "python" 
Sorry, my English is bad :)

### CODE REVIEW

**Comment by GatoLoko** [comment]
As stated in [PEP-394](https://www.python.org/dev/peps/pep-0394/), the "python" command may invoke either python2 or python3.

Python 2.x IS NOT and WILL NOT be supported by Wattpad2Epub, may cause all kinds of malfunctions.

To avoid potential problems, you should always specify "python3".

**Comment by silbaer** [comment]
On Windows the official Python3 is invoked by "python". "python3" does not exists.

**Comment by GatoLoko** [comment]
> On Windows the official Python3 is invoked by "python". "python3" does not exists.

As explained in [python's official documentation](https://docs.python.org/3/using/windows.html), windows releases install all three commands, "python.exe", "python3.exe" and "python3.X.exe" (where the X varies accordingly with the installed version), so "python3" should work in windows too.

What's more, Windows isn't the only system out there. On most linux distributions, "python" is linked to "python2" for historical reasons, and many programs assume it is like that since it was the only alternative at the time. Many distributions still have tools relying on "python" being "python2" and changing it would break all kind of things.

Since we can not assume that "python" will give us what we need, we must point to something that avoids the problem, in this case "python3".

**Comment by silbaer** [comment]
> > On Windows the official Python3 is invoked by "python". "python3" does not exists.
> 
> As explained in [python's official documentation](https://docs.python.org/3/using/windows.html), windows releases install all three commands, "python.exe", "python3.exe" and "python3.X.exe" (where the X varies accordingly with the installed version), so "python3" should work in windows too.

This is only mentioned in the [Microsoft Store package](https://docs.python.org/3/using/windows.html#the-microsoft-store-package). I have installed [The full installer](https://docs.python.org/3/using/windows.html#the-full-installer) and there is no `python3.exe` 

Directory listing of **c:\Program Files\Python38\\**
```

 Verzeichnis von C:\Program Files\Python38

01.07.2020  18:32    <DIR>          .
01.07.2020  18:32    <DIR>          ..
01.07.2020  18:31    <DIR>          DLLs
01.07.2020  18:31    <DIR>          Doc
01.07.2020  18:31    <DIR>          include
01.07.2020  18:31    <DIR>          Lib
01.07.2020  18:31    <DIR>          libs
13.05.2020  22:43            31.453 LICENSE.txt
13.05.2020  22:43           905.782 NEWS.txt
13.05.2020  22:42           100.424 python.exe
13.05.2020  22:42            58.952 python3.dll
13.05.2020  22:42         4.208.200 python38.dll
13.05.2020  22:42            98.888 pythonw.exe
01.07.2020  18:32    <DIR>          Scripts
01.07.2020  18:31    <DIR>          tcl
01.07.2020  18:31    <DIR>          Tools
13.05.2020  22:43           100.880 vcruntime140.dll
13.05.2020  22:43            44.320 vcruntime140_1.dll
               8 Datei(en),      5.548.899 Bytes
              10 Verzeichnis(se), 714.082.328.576 Bytes frei

C:\Program Files\Python38>
```

A little hint like "On Windows you have to use `python` instead of `python3` depending on your python installation." should do it.

**Comment by GatoLoko** [comment]
> This is only mentioned in the [Microsoft Store package](https://docs.python.org/3/using/windows.html#the-microsoft-store-package). I have installed [The full installer](https://docs.python.org/3/using/windows.html#the-full-installer) and there is no `python3.exe`

> A little hint like "On Windows you have to use `python` instead of `python3` depending on your python installation." should do it.

You are right.

In this case, the wording of the original pull request is very imprecise (_"some devices"_), and should be changed to specify it's talking about Windows, and since it's package dependent, that should be included too.

**Pull request closed without merging**
